name: Ubuntu-VM
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Creating User to Login
      run: sudo useradd -m Area69Lab && sudo adduser Area69Lab sudo && echo 'Area69Lab:Area69Lab' | sudo chpasswd
    - name: Installing Desktop Environment (wait for 5 min)
      run: sudo apt-get -qy update && sudo apt-get -qy install ubuntu-desktop
    - name: Installing Xrdp
      run: sudo apt-get -qy install xrdp -y && sudo service xrdp restart
    - name: Installing Ngrok
      run: wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O ngrok.zip && unzip ngrok.zip
    - name: Creating Tunnel
      env:
        ngroktoken: ${{ secrets.NGROK_AUTH_TOKEN }}
      run: |
        ./ngrok authtoken $ngroktoken
        ./ngrok tcp 3389
